- name: Create Vhost User
  user: name={{ usname }}

- name: Create Vhost public_html
  file: path=/home/{{ usname }}/public_html owner={{ usname }} group={{ usname }} mode=0755 state=directory

- name: Create Vhost kibana dir
  file: path=/home/{{ usname }}/public_html/kibana owner={{ usname }} group={{ usname }} mode=0755 state=directory

- name: Create Vhost log directory
  file: path=/home/{{ usname }}/logs owner=root group=root mode=0755 state=directory

- name: Create a placeholder index.html
  template: src=index.j2 dest=/home/{{ usname }}/public_html/index.html owner={{ usname }} group=www-data mode=0644

- name: Create htaccess for user
  template: src=htaccess.j2 dest=/home/{{ usname }}/public_html/.htaccess owner={{ usname }} group={{ usname }} mode=0644

- name: Create htpasswd User
  htpasswd: path=/etc/apache2/passwd name={{ usname }} password={{ pass }} owner=root group=www-data mode=0640

