- name: Install Rsyslog
  apt: pkg={{ item }} update_cache=yes cache_valid_time={{ apt_valid_cache_time }} state=installed
  with_items:
   - rsyslog

- name: Copy Rsyslog Conf
  template: src="rsyslog.j2" dest="/etc/rsyslog.conf" owner=root group=root mode=0644
  notify:
   - restart rsyslog
