---
# This playbook contains common plays that will be run on all nodes.

- name: Update Apt cache
  apt: update_cache=yes cache_valid_time={{ apt_valid_cache_time }}

- name: Install packages
  apt: pkg={{ item }} state=present
  with_items: install_ubuntu_packages
  tags: packages

- name: Remove unused packages
  apt: pkg={{ item }} state=absent
  with_items: remove_ubuntu_packages
  tags: packages